version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  lavalink:
    image: lavalink:latest
    restart: always
    ports:
      - "2333:2333"
  taboo:
    image: taboo:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - lavalink
    volumes:
      - type: bind
        source: ./application.yml
        target: /taboo/application.yml
volumes:
  postgres:
    driver: local
  